[package]
name = "mithril-doc"
version = "0.1.24"
description = "An internal crate to generate documentation."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
include = ["**/*.rs", "Cargo.toml", "README.md", ".gitignore"]

[dependencies]
clap = { workspace = true }
config = { workspace = true }
mithril-doc-derive = { path = "../mithril-doc-derive" }

[dev-dependencies]
mithril-cli-helper = { path = "../mithril-cli-helper" }
regex = "1.11.1"

[features]
default = []
