[package]
name = "mithril-resource-pool"
version = "0.0.4"
description = "Provide a resource pool for Mithril."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
anyhow = { workspace = true }
mithril-common = { path = "../../mithril-common" }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
mithril-common = { path = "../../mithril-common", features = ["test_tools"] }
mockall = { workspace = true }
tokio = { workspace = true, features = ["macros", "time"] }
