[package]
name = "mithril-ticker"
version = "0.1.3"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
mithril-cardano-node-chain = { path = "../cardano-node/mithril-cardano-node-chain" }
mithril-cardano-node-internal-database = { path = "../cardano-node/mithril-cardano-node-internal-database" }
mithril-common = { path = "../../mithril-common" }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
