[package]
name = "mithril-cardano-node-internal-database"
version = "0.1.0"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
mithril-common = { path = "../../../mithril-common" }

[dev-dependencies]
mithril-common = { path = "../../../mithril-common", features = ["test_tools"] }
