name: Nightly Trigger

on:
  # Important note about scheduled workflows:
  # Notifications for scheduled workflows are sent to the user who last modified the cron syntax in the workflow file.
  schedule:
    - cron: "0 2 * * *"
    - cron: "40 16 * * *"

jobs:
  trigger-docker-builds:
    uses: ./.github/workflows/nightly-docker-builds.yml

  trigger-backward-compatibility:
    uses: ./.github/workflows/nightly-backward-compatibility.yml
