name: Nightly Trigger

on:
  # Important note about scheduled workflows:
  # Notifications for scheduled workflows are sent to the user who last modified the cron syntax in the workflow file.
  schedule:
    - cron: "0 2 * * *"
    - cron: "20 11 * * *"
    - cron: "45 11 * * *"

jobs:
  docker-builds:
    uses: ./.github/workflows/nightly-docker-builds.yml

  backward-compatibility:
    uses: ./.github/workflows/nightly-backward-compatibility.yml

  notify-on-failure:
    runs-on: ubuntu-22.04
    needs: [docker-builds, backward-compatibility]
    if: failure()
    steps:
      - name: Send Failure Email
        shell: bash
        run: |
          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
            https://api.mailgun.net/v3/${{ secrets.MAILGUN_DOMAIN }}/messages \
            -F from="GitHub Actions <noreply@${{ secrets.MAILGUN_DOMAIN }}>" \
            -F to="${{ secrets.MAILGUN_TO }}" \
            -F subject="🚨 Nightly Workflow Failed" \
            -F text="**Nightly Trigger** failed, details:

            - **Workflow**: ${{ github.workflow }}
            - **Repository**: ${{ github.repository }}
            - **Run Number**: #${{ github.run_number }}
            - [Verify logs](${{ github.run_url }})"
