name: Notify on Failure

on:
  workflow_dispatch:

jobs:
  notify-on-failure:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        shell: bash
        run: |
          chmod +x ./.github/workflows/scripts/notify-nightly-failure.js

      - name: Send failure notification by email
        uses: peter-evans/sendgrid-action@v1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SCRIPT_FILEPATH: ./.github/workflows/scripts/notify-nightly-failure.js
          SENDGRID_MAIL_FROM: ${{ secrets.CI_NOTIFICATION_EMAIL_FROM }}
          SENDGRID_MAIL_TO: ${{ secrets.CI_NOTIFICATION_EMAIL_TO }}
