name: Test Notify on Failure

on:
  workflow_dispatch:
  workflow_call:

jobs:
  notify-on-failure:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write HTML body to file
        run: |
          cat > ./email-body.html <<EOF
          <h3>Nightly Trigger workflow has failed, see details:</h3>
          <ul>
            <li><strong>Workflow :</strong> ${{ github.workflow }}</li>
            <li><strong>Repository :</strong> ${{ github.repository }}</li>
            <li><strong>Run Number :</strong> #${{ github.run_number }}</li>
            <li><strong>Logs :</strong> <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Check logs</a></li>
          </ul>
          EOF

      - name: Send failure notification via Mailgun
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: ${{ vars.CI_NOTIFICATION_SMTP_SERVER }}
          server_port: ${{ vars.CI_NOTIFICATION_SMTP_PORT }}
          username: ${{ secrets.CI_NOTIFICATION_SMTP_LOGIN }}
          password: ${{ secrets.CI_NOTIFICATION_SMTP_PASSWORD }}
          subject: "🚨 Nightly Workflow Failed"
          to: ${{ secrets.CI_NOTIFICATION_EMAIL_TO }}
          from: ${{ secrets.CI_NOTIFICATION_EMAIL_FROM }}
          html_body: file://email-body.html
